--TB_FATO(ID_FATO, ID_LOCAL, ID_CELULAR, ID_ESTADO_CIVIL, ID_DATA_COMPRA, QUANTIDADE, VALOR)
SELECT
    --SQ_FATO.nextval,
    --dl.ID_LOCAL,
    dp.ID_CELULAR,
    dec.ID_ESTADO_CIVIL,
    --ddc.ID_DATA_COMPRA,
    X.QUANTIDADE,
    X.VALOR
FROM
    (SELECT C.QUANTIDADE, C.VALOR, M.DESCRICAO, CLT.ID_CLIENTE 
        FROM c##OLTP.CARRINHO C 
        join c##OLTP.APARELHO A on (C.ID_APARELHO = A.ID_APARELHO) 
        join c##OLTP.MODELO M on (A.ID_MODELO = M.ID_MODELO)
        join c##OLTP.COMPRA CP on (C.ID_COMPRA = CP.ID_COMPRA)
        join c##OLTP.CLIENTE CLT on (CLT.ID_CLIENTE = CP.ID_CLIENTE)
    )X
JOIN
    TB_CELULAR dp
    ON X.DESCRICAO = dp.MODELO
JOIN
    ESTADO_CIVIL_EXTERNAL_TABLE EXT
    ON X.ID_CLIENTE = EXT.ID_CLIENTE
JOIN
    TB_ESTADO_CIVIL dec
    ON EXT.ESTADO_CIVIL = dec.ESTADO_CIVIL