SET DEFINE OFF

CREATE TABLE ESTADO_CIVIL_EXTERNAL_TABLE (
ID_CLIENTE INTEGER NOT NULL,
ESTADO_CIVIL VARCHAR2(255) NOT NULL);

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (1, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (2, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (3, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (4, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (5, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (6, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (7, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (8, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (9, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (10, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (11, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (12, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (13, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (14, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (15, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (16, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (17, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (18, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (19, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (20, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (21, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (22, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (23, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (24, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (25, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (26, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (27, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (28, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (29, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (30, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (31, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (32, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (33, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (34, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (35, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (36, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (37, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (38, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (39, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (40, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (41, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (42, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (43, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (44, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (45, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (46, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (47, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (48, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (49, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (50, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (51, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (52, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (53, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (54, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (55, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (56, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (57, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (58, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (59, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (60, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (61, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (62, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (63, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (64, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (65, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (66, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (67, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (68, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (69, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (70, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (71, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (72, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (73, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (74, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (75, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (76, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (77, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (78, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (79, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (80, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (81, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (82, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (83, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (84, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (85, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (86, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (87, 'S');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (88, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (89, 'C');

INSERT INTO ESTADO_CIVIL_EXTERNAL_TABLE (ID_CLIENTE, ESTADO_CIVIL) 
VALUES (90, 'C');

SELECT * FROM ESTADO_CIVIL_EXTERNAL_TABLE;

