INSERT INTO TB_FATO(ID_FATO, ID_LOCAL, ID_CELULAR, ID_ESTADO_CIVIL, ID_DATA_COMPRA, QUANTIDADE, VALOR)
SELECT
    SQ_FATO.nextval,
    dl.ID_LOCAL,
    dp.ID_CELULAR,
    dec.ID_ESTADO_CIVIL,
    ddc.ID_DATA_COMPRA,
    X.QUANTIDADE,
    X.VALOR
FROM
    (SELECT 
    C.QUANTIDADE, 
    C.VALOR, 
    M.DESCRICAO, 
    CLT.ID_CLIENTE, 
    CD.DESCRICAO AS CIDADE, 
    E.DESCRICAO AS ESTADO,
    CEIL(TO_NUMBER(extract(month from CP.DATA))/4) AS QUADRIMESTRE, --EXTRAI-SE O MES DO ATRIBUTO DATA (TIPO DATE), CONVERTE PARA NUMBER PARA FINS DE COMPARAÇÃO, DIVIDE POR 4 E ARREDONDA PRA CIMA PARA PEGAR O QUADRIMESTRE CORRETO
    TO_NUMBER(extract(year from CP.DATA)) AS ANO --EXTRAI-SE O ANO DO ATRIBUTO DATA (TIPO DATE), CONVERTE PARA NUMBER PARA FINS DE COMPARAÇÃO
        FROM c##OLTP.CARRINHO C 
        join c##OLTP.APARELHO A on (C.ID_APARELHO = A.ID_APARELHO) --INTERMEDIARIA PARA FILTRAR O MODELO
        join c##OLTP.MODELO M on (A.ID_MODELO = M.ID_MODELO) --FILTRA POR MODELO DO APARELHO, POIS UM MESMO APARELHO NÃO PERTENCE A MARCAS DISTINTAS
        join c##OLTP.COMPRA CP on (C.ID_COMPRA = CP.ID_COMPRA) --INTERMEDIARIA PARA FILTRAR OS DADOS DO CLIENTE; FILTRA PELA DATA DA COMPRA
        join c##OLTP.CLIENTE CLT on (CLT.ID_CLIENTE = CP.ID_CLIENTE) -- INTERMEDIARIA PARA PEGAR OS DADOS DE LOCAL; FILTRA POR ID DO CLIENTE PARA ESTADO CIVIL
        join c##OLTP.CIDADE CD on (CLT.ID_CIDADE = CD.ID_CIDADE) --FILTRA O LOCAL CONJUNTAMENTE COM ESTADO, POIS HÁ CIDADES DUPLICADAS COM SUAS ABREVIAÇÕES
        join c##OLTP.ESTADO E ON (CD.ID_ESTADO = E.ID_ESTADO) --FILTRA O LOCAL JUNTAMENTE COM ESTADO, POIS NÃO HÁ CIDADES COM MESMO NOME EM ESTADOS DIFERENTES NESSE MODELO
    )X
JOIN
    TB_CELULAR dp
    ON X.DESCRICAO = dp.MODELO
JOIN
    ESTADO_CIVIL_EXTERNAL_TABLE EXT
    ON X.ID_CLIENTE = EXT.ID_CLIENTE
JOIN
    TB_ESTADO_CIVIL dec
    ON EXT.ESTADO_CIVIL = dec.ESTADO_CIVIL
JOIN
    TB_LOCAL dl
    on X.CIDADE = dl.CIDADE AND X.ESTADO = dl.ESTADO
JOIN
    TB_DATA_COMPRA ddc
    on X.QUADRIMESTRE = ddc.QUADRIMESTRE AND X.ANO = ddc.ANO;
    
SELECT * FROM TB_FATO;
